### PR TITLE
Adding French locale files. Fixing typos in english locale files.

### PR DESCRIPTION
**Pull request by carronol**
Tested locally, all translations fit properly on my screen.

### CODE REVIEW

**Comment by ay8s** [comment]
Thanks so much @carronol. Will look into the deployment error as I think I need to shift some things around. Will get this deployed as soon as I solve that.

**Comment by ay8s** [comment]
@carronol Perhaps the "Add these race dates & times to your mobile, calendar, Outlook or Google Calendar" could be shortened to something like "Add these race dates & times to your calendar"?

https://share.buffer.com/wbuWmjqQ

**Comment by carronol** [comment]
@ay8s yes this one is a bit long, French is generally more verbose than english
It would be "Ajouter ces dates et horaires de grand Prix à votre calendrier" if you want to change it directly.

**Comment by ay8s** [comment]
👍  Will give it a go, I expect to run into these so we'll also have a think how we can adjust the layout for more verbose languages.

**Comment by ay8s** [comment]
@carronol Just testing this out here https://f1-gwx5prrng.vercel.app/fr

**Pull request merged**
