### PR TITLE
Add locales for Spanish (es)

### PR DESCRIPTION
**Pull request by slopezm**

### CODE REVIEW

**Comment by ay8s** [comment]
Thanks for this @slopezm. I am about to merge https://github.com/sportstimes/f1/pull/74 which has es locale files. Is there anything in there you would change?

**Comment by slopezm** [comment]
#74 looks great. I think the only thing missing is adding 'es' to i18n.json

**Comment by ay8s** [comment]
@slopezm Thanks. I've used a couple of your strings as they were a little shorter. Sorry that you ended up doubling up on the same locale.

**Comment by ay8s** [comment]
@all-contributors please add @slopezm for translations.

**Pull request closed without merging**
