### PR TITLE
Pullrequests/russ k/task/update for new dates

### PR DESCRIPTION
**Pull request by ay8s**

### CODE REVIEW

**Comment by ay8s** [comment]
Includes initial dates/times from #41 along with a few tweaks.

- Removes Virtual GP calendar for now.
- Sets races to TBC
- Hides races that aren't confirmed yet.

**Comment by ay8s** [comment]
Thanks for the PR @Russ-K. I added a couple of additional changes and have deployed it. 👍

**Comment by Russ-K** [comment]
Glad to be of some assistance. 👍

**Comment by ay8s** [comment]
@all-contributors please add @Russ-K for content

**Pull request merged**
