### PR TITLE
[Enhancement] Image F1 track in the pop-up window near the text Gran Prix

### PR DESCRIPTION
**Pull request by HarDX**
[Enhancement] Image F1 track in the pop-up window near the text Gran Prix
I hard reset old pull request, and refactoring this, maybe this is better. No problems with glitch. Can you review this code.
image

### CODE REVIEW

**Comment by ay8s** [comment]
Thanks for this @HarDX. We'll have a think about this in the next few days :)

**Comment by HarDX** [comment]
> Thanks for this @HarDX. We'll have a think about this in the next few days :)

ok, maybe i can add: best lap, last winner to this popup.
And it will be a small info about round

**Comment by ay8s** [comment]
I think ideally the less changeable content the better. Having those extra details adds a little more work each time tracks are introduced/records etc change. 

My initial hesitation for the track image is down to how useful it is and not wanting to overcrowd things. Especially with the introduction of languages and email digests soon.

**Comment by HarDX** [comment]
Maybe close this request?

**Pull request closed without merging**
