### PR TITLE
Create subscribe.json

### PR DESCRIPTION
**Pull request by charley-egmose**
Added to locales/da
I have also added the 5 other locales files - are they still there or should I have PR'ed each?

### CODE REVIEW

**Comment by ay8s** [comment]
@charley-egmose I can only see the subscribe.json. I can grab the other files from your fork if that's easier? 👍

**Comment by charley-egmose** [comment]
Hi Andrew Yates

It seems like, I now was able to commit the JSON files to the da folder.

Best regards,
Charley Egmose

Den lør. 4. jul. 2020 kl. 19.29 skrev Andrew Yates <notifications@github.com

**Comment by charley-egmose** [comment]
Hi again

Well, I haven't been using the git before, but yes, you may be able grab
the files from my fork.

Regards
Charley

Den lør. 4. jul. 2020 kl. 19.29 skrev Andrew Yates <notifications@github.com

**Comment by ay8s** [comment]
@charley-egmose Awesome work without using it before 👍  Will grab them now and get it added to the site. Thanks!

**Comment by charley-egmose** [comment]
Thanks, I will look forward to it👍


Den lør. 4. jul. 2020 kl. 20.15 skrev Andrew Yates <notifications@github.com

**Comment by ay8s** [comment]
@all-contributors please add @charley-egmose for translations.

**Comment by ay8s** [comment]
@charley-egmose This is deploying now :)

**Pull request merged**
