### PR TITLE
Added Ukrainian localization (uk)

### PR DESCRIPTION
**Pull request by sigito**

### CODE REVIEW

**Comment by sigito** [comment]
I’m not sure why I’m fails to deploy with the language been added to `i18n.json`. Should I take that change away?

**Comment by sigito** [comment]
> I’m not sure why it fails to deploy with the language been added to `i18n.json`. Should I take that change away?

Ok, seems like `public/download/uk/index.html` was missing. Added it.

**Comment by ay8s** [comment]
@sigito Thanks, just deployed. Had a branch together already with the uk folder. 👍

**Comment by ay8s** [comment]
@all-contributors please add @sigito for translations.

**Pull request closed without merging**
