### PR TITLE
Add locales for Czech (cz)

### PR DESCRIPTION
**Pull request by adamhoustava**

### CODE REVIEW

**Comment by ay8s** [comment]
@adamhoustava Thanks for these 🙌  

"Přidejte si termíny a časy závodů do svého telefonu, kalendáře, Outlooku nebo Google Kalendáře.",

I wonder if we can adjust this to "Add these race dates & times to your calendar" just to reduce the length a little. I'll be looking at improving the layout to better handle longer strings but this one feels like the "mobile, calendar, Outlook or Google Calendar" isn't really necessary.

**Comment by adamhoustava** [comment]
@ay8s Ok, I'll make it shorter👍

**Comment by ay8s** [comment]
@adamhoustava One last question, wonder if there is any shorter string for TBC? If not I can use "Bude potvrzeno" and make improvements to the layout in the next few days.

**Comment by ay8s** [comment]
Ignore that previous mention, need more coffee while working on all these PRs 👍

**Pull request closed without merging**
