### PR TITLE
Improvements for Albanian (sq) locales

### PR DESCRIPTION
**Pull request by lumbytyci**

### CODE REVIEW

**Comment by lumbytyci** [comment]
Was this merged correctly? I can see it was not deployed.

**Comment by ay8s** [comment]
@lumbytyci Good catch, not sure how that happened. Put a new PR up with the same changes.

**Comment by lumbytyci** [comment]
@ay8s Yep, turns out I submitted PR for merging into master and not main. Anyway, here is the one PR #328

**Comment by ay8s** [comment]
Thanks @lumbytyci 👍

**Pull request merged**
